apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: node-app
  labels:
    app: nodejs-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-db
  template:
    metadata:
      labels:
        app: nodejs-db
    spec:
      containers:
      - name: db-mongo
        image: 094853031708.dkr.ecr.us-east-2.amazonaws.com/aws-capability:db-mongo
        ports:
        - containerPort: 27017
      