apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: NodeApp
  labels:
    app: nodejs-frontend
spec:
  selector:
    app: nodejs-frontend
  type: NodePort
  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
      