apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: node-app
  labels:
    app: nodejs-app
spec:
  selector:
    app: nodejs-app
  type: LoadBalancer
  ports:
    - name: backend
      protocol: TCP
      port: 3080
      targetPort: 3080
      nodePort: 30748
      